version: '3.4'

services:
  authservice:
    image: ${DOCKER_REGISTRY-}authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - 5020:80
      - 5023:443

  categotyservice:
    image: ${DOCKER_REGISTRY-}categotyservice
    build:
      context: .
      dockerfile: ProiectCC/Dockerfile
    ports:
      - 5021:80
      - 5024:443

  expensesservice:
    image: ${DOCKER_REGISTRY-}expensesservice
    build:
      context: .
      dockerfile: ExpensesService/Dockerfile
    ports:
      - 5022:80
      - 5025:443
